In [1]:
!nvidia-smi

Sat Nov 15 07:21:33 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   42C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
from transformers import AutoModelForCausalLM, AutoTokenizer

In [3]:
#Load model and tokenizer

model = AutoModelForCausalLM.from_pretrained(
    "microsoft/phi-3-mini-4k-instruct", 
    device_map = "cuda", 
    trust_remote_code = True, 
)

tokenizer = AutoTokenizer.from_pretrained("microsoft/phi-3-mini-4k-instruct")


/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning: 
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(


config.json:   0%|          | 0.00/967 [00:00<?, ?B/s]

configuration_phi3.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/phi-3-mini-4k-instruct:
- configuration_phi3.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


modeling_phi3.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/microsoft/phi-3-mini-4k-instruct:
- modeling_phi3.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.67G [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/181 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/306 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/599 [00:00<?, ?B/s]

In [4]:
prompt = "Write an email apologizing to sarah for the tragic gardening mishap.Explain how it happened.<|assistant|>"


# Tokenize the input prompt:
input_ids = tokenizer(prompt, return_tensors = "pt").input_ids.to("cuda")

# Generate the text:
generation_output = model.generate(
    input_ids = input_ids, 
    max_new_tokens = 20, 
    use_cache = False
)

# print the output:
print(tokenizer.decode(generation_output[0]))


The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


Write an email apologizing to sarah for the tragic gardening mishap.Explain how it happened.<|assistant|> Subject: Sincere Apologies for the Gardening Mishap

Dear Sarah


In [5]:
print(input_ids)

tensor([[14350,   385,  4876, 27746,  5281,   304, 22887,   801,   363,   278,
         25305,   293, 16423,   292,   286,   728,   481, 29889,  9544,  7420,
           920,   372,  9559, 29889, 32001]], device='cuda:0')


In [6]:
for id in input_ids[0]:
    print(tokenizer.decode(id))

Write
an
email
apolog
izing
to
sar
ah
for
the
trag
ic
garden
ing
m
ish
ap
.
Exp
lain
how
it
happened
.
<|assistant|>


## Tokenization method:

### 1. byte pair encoding
### 2. WordPiece

In [7]:
text = """
English and CAPITALIZATION 

show_tokens False None elif == >= else: two tabs: "  " Three tabs:"    "

12.0 * 50 = 600
"""

In [8]:
colors_list = ['102;194;165', '252;141;98', '141;160;203', 
               '231;138;195', '166;216;84', '255;217;47']

def show_tokens(sentence, tokenizer_name):
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
    token_ids = tokenizer(sentence).input_ids
    for idx, t in enumerate(token_ids):
        print(f'\x1b[0;30;48;2;{colors_list[idx % len(colors_list)]}m' + 
              tokenizer.decode(t) + 
              '\x1b[0m', 
              end = ' '
              )

In [9]:
show_tokens(sentence = text, tokenizer_name = 'microsoft/phi-3-mini-4k-instruct')

 
 English and C AP IT AL IZ ATION  
 
 show _ to kens False None elif == >= else : two tabs : "  " Three tabs :"    " 
 
 1 2 . 0 *  5 0 =  6 0 0 
 

In [10]:
from transformers import AutoModel, AutoTokenizer

In [11]:
# Load a tokenizer
tokenizer = AutoTokenizer.from_pretrained('microsoft/deberta-base')

# Load a language model
model = AutoModel.from_pretrained('microsoft/deberta-v3-xsmall')

#tokenize the sentence
tokens = tokenizer('Hello world', return_tensors = 'pt')

#process the tokens
output = model(**tokens)[0]


tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/474 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/578 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/241M [00:00<?, ?B/s]

In [12]:
output.shape

torch.Size([1, 4, 384])

In [13]:
for token in tokens['input_ids'][0]:
    print(tokenizer.decode(token))


[CLS]
Hello
 world
[SEP]


In [14]:
output

tensor([[[-3.4816,  0.0861, -0.1819,  ..., -0.0612, -0.3911,  0.3017],
         [ 0.1898,  0.3208, -0.2315,  ...,  0.3714,  0.2478,  0.8048],
         [ 0.2071,  0.5036, -0.0485,  ...,  1.2175, -0.2292,  0.8582],
         [-3.4278,  0.0645, -0.1427,  ...,  0.0658, -0.4367,  0.3834]]],
       grad_fn=<NativeLayerNormBackward0>)

model.safetensors:   0%|          | 0.00/241M [00:00<?, ?B/s]

In [15]:
from sentence_transformers import SentenceTransformer

In [16]:
# Load model
model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")

# Convert text to text embeddings
vector = model.encode("Best movie ever!")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [17]:
vector.shape

(768,)

In [18]:
vector

array([-2.02203933e-02,  4.57696877e-02, -1.26637146e-02, -3.37991631e-03,
       -2.54910300e-03, -3.31096235e-03, -4.58366945e-02,  2.32390799e-02,
       -3.12585123e-02, -3.15588824e-02, -2.19783355e-02,  3.67821753e-03,
        3.39105981e-03, -1.88130587e-02, -2.65821870e-02, -1.45892315e-02,
        3.20066400e-02, -3.66493082e-03,  1.75410733e-02,  5.43209612e-02,
       -3.96661647e-02,  9.93637647e-03, -3.27205285e-02, -1.62909944e-02,
        6.36525359e-03, -1.24459760e-02,  1.04737049e-02,  3.08674313e-02,
        7.47453189e-03, -3.86319868e-02, -6.19924963e-02, -3.25308628e-02,
       -1.40268244e-02,  5.16586639e-02,  1.69651707e-06, -1.74092929e-04,
       -1.27881172e-03, -4.15052772e-02,  5.00347884e-03,  4.58600894e-02,
       -2.85337027e-02,  5.02370670e-02, -1.75183658e-02, -3.98830482e-04,
        1.63311344e-02,  5.89936748e-02, -2.21730098e-02, -4.00975086e-02,
       -6.60439581e-03, -2.97632981e-02, -3.18221636e-02, -1.77945811e-02,
       -1.54363075e-02, -

In [19]:
pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 72.3 MB/s eta 0:00:00:00:0100:01


In [20]:
import gensim.downloader as api

In [21]:
model = api.load("glove-wiki-gigaword-50")

[==================================================] 100.0% 66.0/66.0MB downloaded


In [22]:
model.most_similar([model["king"]], topn = 20)

[('king', 1.0000001192092896),
 ('prince', 0.8236179351806641),
 ('queen', 0.7839043140411377),
 ('ii', 0.7746230363845825),
 ('emperor', 0.7736247777938843),
 ('son', 0.766719400882721),
 ('uncle', 0.7627150416374207),
 ('kingdom', 0.7542161345481873),
 ('throne', 0.7539914846420288),
 ('brother', 0.7492411136627197),
 ('ruler', 0.7434253692626953),
 ('grandson', 0.7404318451881409),
 ('lord', 0.7388724088668823),
 ('father', 0.7335717678070068),
 ('iv', 0.7283055782318115),
 ('reign', 0.726709246635437),
 ('name', 0.7214821577072144),
 ('monarch', 0.7193011045455933),
 ('nephew', 0.7188021540641785),
 ('iii', 0.7184330821037292)]

### Training a Song embedding model:

In [23]:
import pandas as pd
from urllib import request

In [24]:
# Get the playlist dataset file

data = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/train.txt')

# Parse the playlist dataset file. Skip the first two lines as 
# they only contain metadata
lines = data.read().decode("utf-8").split('\n')[2:]

# Remove playlists with only one song
playlists = [s.rstrip().split() for s in lines if len(s.split()) > 1]

# Load song metadata
songs_file = request.urlopen('https://storage.googleapis.com/maps-premium/dataset/yes_complete/song_hash.txt')
songs_file = songs_file.read().decode("utf-8").split("\n")
songs = [s.rstrip().split('\t') for s in songs_file]
songs_df = pd.DataFrame(data = songs, columns = ["id", "title", "artist"])
songs_df = songs_df.set_index("id")
print("playlist #1: \n", playlists[0], '\n')
print("playlist #2:\n", playlists[1])

playlist #1: 
 ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '2', '42', '43', '44', '45', '46', '47', '48', '20', '49', '8', '50', '51', '52', '53', '54', '55', '56', '57', '25', '58', '59', '60', '61', '62', '3', '63', '64', '65', '66', '46', '47', '67', '2', '48', '68', '69', '70', '57', '50', '71', '72', '53', '73', '25', '74', '59', '20', '46', '75', '76', '77', '59', '20', '43'] 

playlist #2:
 ['78', '79', '80', '3', '62', '81', '14', '82', '48', '83', '84', '17', '85', '86', '87', '88', '74', '89', '90', '91', '4', '73', '62', '92', '17', '53', '59', '93', '94', '51', '50', '27', '95', '48', '96', '97', '98', '99', '100', '57', '101', '102', '25', '103', '3', '104', '105', '106', '107', '47', '108', '109', '110', '111', '112', '113', '25', '63', '62', '114', '115', '84', '116', '117', 

In [25]:
from gensim.models import Word2Vec

In [26]:
# Train our word2vec model

model = Word2Vec(
    playlists, vector_size = 32, window = 20, negative = 50, min_count = 1, workers = 4
)


In [27]:
song_id = 2172

# ask the model for songs similar to song #2172

model.wv.most_similar(positive = str(song_id))

[('2849', 0.9989483952522278),
 ('2976', 0.9983005523681641),
 ('5549', 0.9982288479804993),
 ('3094', 0.997631311416626),
 ('2886', 0.9970257878303528),
 ('2688', 0.9962048530578613),
 ('2715', 0.9962006211280823),
 ('3136', 0.9961579442024231),
 ('2640', 0.9960967898368835),
 ('2704', 0.9956125020980835)]

In [28]:
print(songs_df.iloc[2172])

title     Fade To Black
artist        Metallica
Name: 2172 , dtype: object


In [29]:
import numpy as np

In [30]:
def print_recommendations(song_id):
    similar_songs = np.array(
        model.wv.most_similar(positive = str(song_id), topn = 5)
    )[:, 0]
    return songs_df.iloc[similar_songs]

# Extract recommendations

print_recommendations(2172)

title         artist
id                                    
2849   Run To The Hills    Iron Maiden
2976       I Don't Know  Ozzy Osbourne
5549      November Rain  Guns N' Roses
3094   Breaking The Law   Judas Priest
2886            The Zoo      Scorpions